image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build
    init: |
      mkdir -p .idea
      cp etc/.idea/* .idea
      mvn clean install

jetbrains:
  intellij:
    plugins:
      - com.intellij.plugin.adernov.powershell